@startuml contexto
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
AddRelTag("async", $lineStyle = DashedLine())
SHOW_PERSON_PORTRAIT()

title "Codeflix: Projeto Prático do Curso Full Cycle"

System_Boundary(gateway, "Codeflix") {
    System(kafka_connect,"Kafka Connect", "Serviço de replicação de dados do catálogo")
    System(frontend_catalogo_admin,"Frontend: Admin do Catálogo de Vídeos","SPA que gerencia os vídeos, incluindo as categorias e gêneros")
    System(encoder_de_video,"Encoder de Vídeos","Realiza o encoding dos vídeos para mpeg-dash")

   System_Boundary(catalogo, "Backend: Admin do Catálogo de Vídeos") {
      Container(app, "App", "Linguagem livre", "Sistema que gerencia os vídeos incluindo as categorieas e gêneros")
      ContainerDb(banco_de_dados, "Banco de dados", "MySQL", "Armazena os dados do catálogo")
      Container(bucket_de_videos, "Bucket de vídeos", "Google, Cloud Storage", "Armazena os vídeos brutos")

      Rel(frontend_catalogo_admin, app, "Interege com via", "HTTPS")
      Rel(kafka_connect, banco_de_dados, "Copia dados usando connector", "Debezium MySQL")
      Rel(encoder_de_video, app, "Consome dados do video convertido via", "Fila: videos.converted", $tags="async")
      Rel(app, encoder_de_video, "Publica dados do vídeo recém criado via", "Fila: videos.new", $tags="async")

      Rel(app, banco_de_dados, "Interege com via", "SQL")
      Rel(app, bucket_de_videos, "Faz upload de vídeo via", "HTTPS")
   }
}
@enduml